name: Build and Deploy .NET Web API to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: dotnet publish MyApiGithubActions.csproj -c Release -o out

    - name: Copy published files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "out/*"
        target: "~/MyApiGithubActions"

    - name: Restart API on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          pkill -f "dotnet MyApiGithubActions.dll" || true
          cd ~/MyApiGithubActions
          ls -al
          if [ -f "MyApiGithubActions.dll" ]; then
            nohup dotnet MyApiGithubActions.dll --urls "http://*:5000" > myapi.log 2>&1 &
            sleep 2
            if curl -s http://localhost:5000/swagger > /dev/null; then
              echo "Application started successfully and Swagger reachable."
            else
              echo "Warning: App started but Swagger not available. Check myapi.log."
            fi
          else
            echo "Error: MyApiGithubActions.dll not found!"
            exit 1
          fi
