name: Build and Deploy .NET Web API to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: dotnet publish MyApiGithubActions.csproj -c Release -o out

    - name: Copy published files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "out/*"
        target: "~/MyApiGithubActions/out"

    - name: Restart API on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Kill the running app process if any
          pkill -f "dotnet MyApiGithubActions.dll" || true
          # Navigate to the deployment directory
          cd ~/MyApiGithubActions/out
          # Debug: List files to verify DLL presence
          ls -al
          # Start the application if the DLL exists
          if [ -f "MyApiGithubActions.dll" ]; then
            nohup dotnet MyApiGithubActions.dll --urls "http://*:5000" > myapi.log 2>&1 &
            echo "Application started successfully."
          else
            echo "Error: MyApiGithubActions.dll not found in ~/MyApiGithubActions/out"
            exit 1
          fi
